import { SkillDef, SocialPlatform } from "./types";

export const PREDEFINED_SKILLS: SkillDef[] = [
  {
    id: "html",
    name: "HTML",
    color: "#E34F26",
    logo: "html5",
    category: "Languages",
  },
  {
    id: "css",
    name: "CSS",
    color: "#1572B6",
    logo: "css3",
    category: "Languages",
  },
  {
    id: "javascript",
    name: "JavaScript",
    color: "#F7DF1E",
    logo: "javascript",
    category: "Languages",
  },
  {
    id: "typescript",
    name: "TypeScript",
    color: "#3178C6",
    logo: "typescript",
    category: "Languages",
  },
  {
    id: "python",
    name: "Python",
    color: "#3776AB",
    logo: "python",
    category: "Languages",
  },
  {
    id: "java",
    name: "Java",
    color: "#007396",
    logo: "openjdk",
    category: "Languages",
  },
  { id: "go", name: "Go", color: "#00ADD8", logo: "go", category: "Languages" },
  {
    id: "rust",
    name: "Rust",
    color: "#DEA584",
    logo: "rust",
    category: "Languages",
  },
  {
    id: "csharp",
    name: "C#",
    color: "#239120",
    logo: "csharp",
    category: "Languages",
  },
  {
    id: "cpp",
    name: "C++",
    color: "#00599C",
    logo: "cpp",
    category: "Languages",
  },
  {
    id: "php",
    name: "PHP",
    color: "#777BB4",
    logo: "php",
    category: "Languages",
  },
  {
    id: "ruby",
    name: "Ruby",
    color: "#CC342D",
    logo: "ruby",
    category: "Languages",
  },
  {
    id: "swift",
    name: "Swift",
    color: "#FA7343",
    logo: "swift",
    category: "Languages",
  },
  {
    id: "kotlin",
    name: "Kotlin",
    color: "#7F52FF",
    logo: "kotlin",
    category: "Languages",
  },
  {
    id: "dart",
    name: "Dart",
    color: "#0175C2",
    logo: "dart",
    category: "Languages",
  },
  {
    id: "scala",
    name: "Scala",
    color: "#DC322F",
    logo: "scala",
    category: "Languages",
  },
  { id: "r", name: "R", color: "#276DC3", logo: "r", category: "Languages" },
  {
    id: "matlab",
    name: "MATLAB",
    color: "#E16737",
    logo: "mathworks",
    category: "Languages",
  },
  {
    id: "vercel",
    name: "Vercel",
    color: "#000000",
    logo: "vercel",
    category: "Hosting",
  },
  {
    id: "netlify",
    name: "Netlify",
    color: "#00C7B7",
    logo: "netlify",
    category: "Hosting",
  },
  {
    id: "aws",
    name: "AWS",
    color: "#FF9900",
    logo: "amazonaws",
    category: "Hosting",
  },
  {
    id: "azure",
    name: "Azure",
    color: "#0078D4",
    logo: "microsoftazure",
    category: "Hosting",
  },
  {
    id: "gcp",
    name: "GCP",
    color: "#4285F4",
    logo: "googlecloud",
    category: "Hosting",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    color: "#F48120",
    logo: "cloudflare",
    category: "Hosting",
  },
  {
    id: "heroku",
    name: "Heroku",
    color: "#430098",
    logo: "heroku",
    category: "Hosting",
  },
  {
    id: "firebase",
    name: "Firebase",
    color: "#FFCA28",
    logo: "firebase",
    category: "Hosting",
  },
  {
    id: "docker",
    name: "Docker",
    color: "#2496ED",
    logo: "docker",
    category: "Hosting",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    color: "#326CE5",
    logo: "kubernetes",
    category: "Hosting",
  },
  {
    id: "terraform",
    name: "Terraform",
    color: "#7B42BC",
    logo: "terraform",
    category: "Hosting",
  },
  {
    id: "react",
    name: "React",
    color: "#61DAFB",
    logo: "react",
    category: "Frameworks & Libraries",
  },
  {
    id: "vue",
    name: "Vue",
    color: "#4FC08D",
    logo: "vuedotjs",
    category: "Frameworks & Libraries",
  },
  {
    id: "angular",
    name: "Angular",
    color: "#DD0031",
    logo: "angular",
    category: "Frameworks & Libraries",
  },
  {
    id: "nextjs",
    name: "Next.js",
    color: "#000000",
    logo: "nextdotjs",
    category: "Frameworks & Libraries",
  },
  {
    id: "nuxtjs",
    name: "Nuxt.js",
    color: "#00DC82",
    logo: "nuxtdotjs",
    category: "Frameworks & Libraries",
  },
  {
    id: "svelte",
    name: "Svelte",
    color: "#FF3E00",
    logo: "svelte",
    category: "Frameworks & Libraries",
  },
  {
    id: "tailwind",
    name: "Tailwind",
    color: "#06B6D4",
    logo: "tailwindcss",
    category: "Frameworks & Libraries",
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    color: "#7952B3",
    logo: "bootstrap",
    category: "Frameworks & Libraries",
  },
  {
    id: "jquery",
    name: "jQuery",
    color: "#0769AD",
    logo: "jquery",
    category: "Frameworks & Libraries",
  },
  {
    id: "nodejs",
    name: "Node.js",
    color: "#339933",
    logo: "nodejs",
    category: "Frameworks & Libraries",
  },
  {
    id: "express",
    name: "Express",
    color: "#000000",
    logo: "express",
    category: "Frameworks & Libraries",
  },
  {
    id: "django",
    name: "Django",
    color: "#092E20",
    logo: "django",
    category: "Frameworks & Libraries",
  },
  {
    id: "flask",
    name: "Flask",
    color: "#000000",
    logo: "flask",
    category: "Frameworks & Libraries",
  },
  {
    id: "spring",
    name: "Spring",
    color: "#6DB33F",
    logo: "spring",
    category: "Frameworks & Libraries",
  },
  {
    id: "dotnet",
    name: ".NET",
    color: "#512BD4",
    logo: "dotnet",
    category: "Frameworks & Libraries",
  },
  {
    id: "laravel",
    name: "Laravel",
    color: "#FF2D20",
    logo: "laravel",
    category: "Frameworks & Libraries",
  },
  {
    id: "flutter",
    name: "Flutter",
    color: "#02569B",
    logo: "flutter",
    category: "Frameworks & Libraries",
  },
  {
    id: "reactnative",
    name: "React Native",
    color: "#61DAFB",
    logo: "react",
    category: "Frameworks & Libraries",
  },
  {
    id: "graphql",
    name: "GraphQL",
    color: "#E10098",
    logo: "graphql",
    category: "Frameworks & Libraries",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    color: "#47A248",
    logo: "mongodb",
    category: "Database & Server",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    color: "#4169E1",
    logo: "postgresql",
    category: "Database & Server",
  },
  {
    id: "mysql",
    name: "MySQL",
    color: "#4479A1",
    logo: "mysql",
    category: "Database & Server",
  },
  {
    id: "redis",
    name: "Redis",
    color: "#DC382D",
    logo: "redis",
    category: "Database & Server",
  },
  {
    id: "sqlite",
    name: "SQLite",
    color: "#003B57",
    logo: "sqlite",
    category: "Database & Server",
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    color: "#FEC514",
    logo: "elasticsearch",
    category: "Database & Server",
  },
  {
    id: "nginx",
    name: "NGINX",
    color: "#009639",
    logo: "nginx",
    category: "Database & Server",
  },
  {
    id: "apache",
    name: "Apache",
    color: "#D22128",
    logo: "apache",
    category: "Database & Server",
  },
  {
    id: "mariadb",
    name: "MariaDB",
    color: "#003545",
    logo: "mariadb",
    category: "Database & Server",
  },
  {
    id: "figma",
    name: "Figma",
    color: "#F24E1E",
    logo: "figma",
    category: "Design",
  },
  {
    id: "adobexd",
    name: "Adobe XD",
    color: "#FF61F6",
    logo: "adobe",
    category: "Design",
  },
  {
    id: "sketch",
    name: "Sketch",
    color: "#F7B500",
    logo: "sketch",
    category: "Design",
  },
  {
    id: "photoshop",
    name: "Photoshop",
    color: "#31A8FF",
    logo: "adobe",
    category: "Design",
  },
  {
    id: "illustrator",
    name: "Illustrator",
    color: "#FF9A00",
    logo: "adobe",
    category: "Design",
  },
  {
    id: "sass",
    name: "SASS",
    color: "#CC6699",
    logo: "sass",
    category: "Design",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    color: "#FF6F00",
    logo: "tensorflow",
    category: "ML / DL",
  },
  {
    id: "pytorch",
    name: "PyTorch",
    color: "#EE4C2C",
    logo: "pytorch",
    category: "ML / DL",
  },
  {
    id: "keras",
    name: "Keras",
    color: "#D00000",
    logo: "keras",
    category: "ML / DL",
  },
  {
    id: "scikitlearn",
    name: "Scikit-learn",
    color: "#F7931E",
    logo: "scikitlearn",
    category: "ML / DL",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    color: "#FFD21E",
    logo: "huggingface",
    category: "ML / DL",
  },
  {
    id: "opencv",
    name: "OpenCV",
    color: "#5C3EE8",
    logo: "opencv",
    category: "ML / DL",
  },
  {
    id: "pandas",
    name: "Pandas",
    color: "#150458",
    logo: "pandas",
    category: "ML / DL",
  },
  {
    id: "numpy",
    name: "NumPy",
    color: "#013243",
    logo: "numpy",
    category: "ML / DL",
  },
  {
    id: "githubactions",
    name: "GitHub Actions",
    color: "#2088FF",
    logo: "githubactions",
    category: "CI / CD",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    color: "#D24939",
    logo: "jenkins",
    category: "CI / CD",
  },
  {
    id: "gitlabci",
    name: "GitLab CI",
    color: "#FC6D26",
    logo: "gitlab",
    category: "CI / CD",
  },
  {
    id: "travisci",
    name: "Travis CI",
    color: "#E2096E",
    logo: "travisci",
    category: "CI / CD",
  },
  {
    id: "circleci",
    name: "CircleCI",
    color: "#343434",
    logo: "circleci",
    category: "CI / CD",
  },
  {
    id: "argo",
    name: "Argo CD",
    color: "#EF7B4D",
    logo: "argo",
    category: "CI / CD",
  },
  {
    id: "jest",
    name: "Jest",
    color: "#C21325",
    logo: "jest",
    category: "Testing",
  },
  {
    id: "mocha",
    name: "Mocha",
    color: "#8D6748",
    logo: "mocha",
    category: "Testing",
  },
  {
    id: "cypress",
    name: "Cypress",
    color: "#69D3A7",
    logo: "cypress",
    category: "Testing",
  },
  {
    id: "selenium",
    name: "Selenium",
    color: "#43B02A",
    logo: "selenium",
    category: "Testing",
  },
  {
    id: "pytest",
    name: "Pytest",
    color: "#0A9EDC",
    logo: "pytest",
    category: "Testing",
  },
  {
    id: "junit",
    name: "JUnit",
    color: "#25A162",
    logo: "junit5",
    category: "Testing",
  },
  {
    id: "storybook",
    name: "Storybook",
    color: "#FF4785",
    logo: "storybook",
    category: "Testing",
  },
  { id: "git", name: "Git", color: "#F05032", logo: "git", category: "Others" },
  {
    id: "github",
    name: "GitHub",
    color: "#181717",
    logo: "github",
    category: "Others",
  },
  {
    id: "gitlab",
    name: "GitLab",
    color: "#FC6D26",
    logo: "gitlab",
    category: "Others",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    color: "#0052CC",
    logo: "bitbucket",
    category: "Others",
  },
  {
    id: "linux",
    name: "Linux",
    color: "#FCC624",
    logo: "linux",
    category: "Others",
  },
  {
    id: "ubuntu",
    name: "Ubuntu",
    color: "#E95420",
    logo: "ubuntu",
    category: "Others",
  },
  {
    id: "windows",
    name: "Windows",
    color: "#0078D6",
    logo: "windows",
    category: "Others",
  },
  {
    id: "macos",
    name: "macOS",
    color: "#000000",
    logo: "apple",
    category: "Others",
  },
  {
    id: "raspberrypi",
    name: "Raspberry Pi",
    color: "#A22846",
    logo: "raspberrypi",
    category: "Others",
  },
];

export const SKILL_CATEGORIES = [
  "Languages",
  "Hosting",
  "Frameworks & Libraries",
  "Database & Server",
  "Design",
  "ML / DL",
  "CI / CD",
  "Testing",
  "Others",
];

export const SOCIAL_PLATFORMS: SocialPlatform[] = [
  {
    id: "facebook",
    name: "Facebook",
    logo: "facebook",
    color: "#1877F2",
    type: "url",
    baseUrl: "https://facebook.com/",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    logo: "linkedin",
    color: "#0A66C2",
    type: "url",
    baseUrl: "https://linkedin.com/in/",
  },
  {
    id: "youtube",
    name: "YouTube",
    logo: "youtube",
    color: "#FF0000",
    type: "url",
    baseUrl: "https://youtube.com/@",
  },
  {
    id: "email",
    name: "Email",
    logo: "gmail",
    color: "#EA4335",
    type: "email",
  },
  {
    id: "discord",
    name: "Discord",
    logo: "discord",
    color: "#5865F2",
    type: "url",
    baseUrl: "https://discord.com/invite/",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    logo: "pinterest",
    color: "#E60023",
    type: "url",
    baseUrl: "https://pinterest.com/",
  },
  {
    id: "quora",
    name: "Quora",
    logo: "quora",
    color: "#B92B27",
    type: "url",
    baseUrl: "https://quora.com/profile/",
  },
  {
    id: "x",
    name: "X",
    logo: "x",
    color: "#000000",
    type: "username",
    baseUrl: "https://x.com/",
  },
  {
    id: "codepen",
    name: "CodePen",
    logo: "codepen",
    color: "#000000",
    type: "username",
    baseUrl: "https://codepen.io/",
  },
  {
    id: "twitch",
    name: "Twitch",
    logo: "twitch",
    color: "#9146FF",
    type: "username",
    baseUrl: "https://twitch.tv/",
  },
  {
    id: "medium",
    name: "Medium",
    logo: "medium",
    color: "#000000",
    type: "username",
    baseUrl: "https://medium.com/@",
  },
  {
    id: "instagram",
    name: "Instagram",
    logo: "instagram",
    color: "#E4405F",
    type: "username",
    baseUrl: "https://instagram.com/",
  },
  {
    id: "bluesky",
    name: "Bluesky",
    logo: "bluesky",
    color: "#0085FF",
    type: "username",
    baseUrl: "https://bsky.app/profile/",
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    logo: "stackoverflow",
    color: "#F48024",
    type: "url",
    baseUrl: "https://stackoverflow.com/users/",
  },
];
